name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build image')"
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mandatory to use the extract version from tag action
          
      - name: Extract version from tag
        id: get_version
        uses: damienaicheh/extract-version-from-tag-action@v1.3.0    

      - name: Display version
        run: echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            thegenuinedockeruser/cv-chatbot:${{ env.VERSION }}
            thegenuinedockeruser/cv-chatbot:latest
          platforms: linux/amd64,linux/arm64


          